package tn.esprit.pdm.Models

data class VinDetails(
    val make: String?,                      // Marque (ex. Volkswagen)
    val model: String?,                     // Modèle (ex. Golf)
    val modelYear: String?,                 // Année modèle (ex. 2002)
    val bodyStyle: String?,                 // Style de carrosserie (ex. 3/5 Doors Hatchback)
    val engineType: String?,                // Type de moteur (ex. 1.9L FWD)
    val fuelType: String?,                  // Type de carburant (ex. Diesel)
    val vehicleClass: String?,              // Classe du véhicule (ex. Compact Car)
    val vehicleType: String?,               // Type de véhicule (ex. Passenger car)
    val manufacturedIn: String?,            // Fabriqué en (ex. Germany)
    val manufacturer: String?,              // Fabricant (ex. Volkswagen AG)
    val addressLine1: String?,              // Adresse ligne 1 (ex. Wolfsburg/Hannover)
    val addressLine2: String?,              // Adresse ligne 2 (ex. Wolfsburg/Hannover)
    val region: String?,                    // Région (ex. Europe)
    val country: String?,                   // Pays (ex. Germany)
    val note: String?,                      // Remarque (ex. Manufacturer builds more than 500 vehicles per year)
    val bodyType: String?,                  // Type de carrosserie (ex. Hatchback)
    val numberOfDoors: String?,             // Nombre de portes (ex. 3/5)
    val numberOfSeats: String?,             // Nombre de sièges (ex. 5)
    val displacementSi: String?,            // Cylindrée en SI (ex. 1896)
    val displacementCid: String?,           // Cylindrée en CID (ex. 116)
    val displacementNominal: String?,       // Cylindrée nominale (ex. 1.9)
    val engineHorsepower: String?,          // Puissance moteur (ex. 68)
    val engineKilowatts: String?,           // Kilowatts moteur (ex. 50)
    val emissionStandard: String?,          // Norme d'émission (ex. Euro 4)
    val driveline: String?,                 // Transmission (ex. FWD)
    val antiBrakeSystem: String?,           // ABS (ex. ABS)
    val equipment: List<String>?,           // Liste des équipements (ex. Power Steering)
    val optionalEquipment: List<String>?    // Liste des équipements optionnels (ex. Cruise control, Traction control)
)
